services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: entregable4
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  m5-entregable4:
    image: pcosio05/m5-entregable4:0.0.3
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
volumes:
  db_data: 